services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: data-backend/Dockerfile
    contextPath: data-backend
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    contextPath: frontend
    envVars:
      - key: PORT
        value: 8501
