services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./data-backend/Dockerfile
    buildContext: ./data-backend
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    buildContext: ./frontend
    envVars:
      - key: PORT
        value: 8501
    dependsOn:
      - backend

