services:
  - type: web
    name: backend
    env: docker
    plan: free
    repo: https://github.com/your-username/your-repo  # Optional if deploying from GitHub
    dockerfilePath: data-backend/Dockerfile
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: PORT
        value: 8501